---
- name: Install Git, Python3, Flask, and clone the repository on Raspberry Pi
  hosts: raspberry_pi
  become: yes
  vars:
    repo_url: "https://git.ece.iastate.edu/sd/sddec23-03.git"
    destination_folder: "/home/pi/Desktop/sddec23-03"
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: safe

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask
      pip:
        name: Flask
        state: present
        executable: pip3

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ destination_folder }}"
        clone: yes
        update: yes
      become: no
      become_user: pi
